spring:
  application:
    name: java-server-side-ui
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Admin123!
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true